[package]
name = "type_down"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Wehmoeller"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
parasite = { path = "../parasite" }
ariadne = "0.4.0"
