[package]
name = "type_down"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Wehmoeller"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
parasite = { path = "../parasite" }
miette = { version = "7.1.0", features = ["fancy"] }
thiserror = "1.0"
html-writer = { path = "crates/html-writer" }
pandoc_ast = "0.8.6"
pandoc = { version = "0.8.11", optional = true }

[features]
default = ["pdf", "docx", "html"]
pdf = ["pandoc"]
docx = ["pandoc"]
html = []

[workspace]
members = ["crates/*"]
