[package]
name = "type_down"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Wehmoeller"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
miette = { version = "7.1.0", features = ["fancy"] }
thiserror = "1.0"
tyd-syntax = { path = "crates/tyd-syntax" }
tyd-render = { path = "crates/tyd-render" }
tyd-pandoc = { path = "crates/tyd-pandoc" }
# tyd-html = { path = "crates/tyd-html", optional = true }

[features]
# default = ["pdf", "docx", "html"]
# pdf = ["pandoc"]
# docx = ["pandoc"]
# html = []
default = []
# html = ["tyd-html"]

[workspace]
members = [
    # "crates/*"
    "crates/tyd-language-server",
    "crates/tyd-pandoc",
    "crates/tyd-render",
    "crates/tyd-syntax",
]
