[package]
name = "type_down"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Wehmoeller"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
parasite = { path = "../parasite" }
miette = { version = "7.1.0", features = ["fancy"] }
thiserror = "1.0"
enum-map = "2.7"
pdf-writer = { version = "0.9.2", optional = true }
docx-rs = { version = "0.4.8", optional = true }

[features]
default = ["pdf", "docx"]
pdf = ["pdf-writer"]
docx = ["docx-rs"]
