[package]
name = "tyd-html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tyd-syntax = { path = "../tyd-syntax" }
tyd-eval = { path = "../tyd-eval" }
miette = "7.1.0"
thiserror = "1.0"
